### ISSUE TITLE
Can you let us use 1920x1080 resolution?

### ISSUE THREAD

**Issue by ademumutakbas** [Ceohh/Automatic-Rain-For-Bandit.Camp#1]
Can you let us use 1920x1080 resolution? It is not worth to use on 1650x1080. I would like to support you anyways if it works well but I can't even use it.

**Comment by Ceohh** [comment]
To use it in 1920x1080 all you would have to do is adjust the on screen values for 1920x1080
something simple like ahk's windowspy can help you do that (Get on screen coordinates).

You need the coordinates of the box for rain and the box to bypass captcha that is all.

I will look into automatic resolution adjustment.

**Comment by ademumutakbas** [comment]
Sorry, I don't have a such coding profession. I also didn't understand how the script works. Is it joining when it see Join Rain button or something like that? I couldn't try it because of resolution problem. I will wait for 1920x1080 automatic resolution adjustment. I hope you gonna develop it. :) Thanks from now on.

**Comment by ademumutakbas** [comment]
It worked somehow on the 1920x1080 by the way. Chat must be on the left side.
